// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "percent.h"

/////////////////////////////////////////////////////////////////////////////
// CPercent

IMPLEMENT_DYNCREATE(CPercent, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPercent properties

/////////////////////////////////////////////////////////////////////////////
// CPercent operations
